DNA = "GGGGTAGAGTAGCATCCAGATGTTCGGATTAAGCTAGCAGTCAGACCACCTGAGAAATAGTAGGCTGGAGTTCAAACTAGCAGGATGGGATTCGGCAACACGTATGCGCTGCTAATGCCAAATGTAACTAACGGGGAGTCAAAAGGTAGGGTCCAAAAGCTCGACCTGGCATAAACCCTTTTCCGGCATGACCGTATGTCGTAAACTCCTCTATCCACCGTCCTGCCGCTCGCATCCTCCCTTCCATGGCTCGTACACACGGGCAATCTGAGATCGTGAAATTACAATCTCACTTCTATTAACAGATAACTGTCTCCCCGTAATCCTTTAATATCTTCCCAATGTACCCGGGAGAACGCGCTCATGCCGATCGTTACGAAGTGATCATCCTCTCGGGTTAGAAAAGCATTCCCTAAAGGGTACATCGCGCTTACCCTAATCTCAAATTGACTGCTACTCGTTTGTTCGATCCAATCTAGGTCCGGGCCATCGTCGATCGTAGATACGCGAGTCTGTAATGTATTAAGTTATATGAAAGCTAGTGCCCGACTATTGCACCTCGAGGAGGTGACAGCCTCCCCGTGGTAATGTCACGCTAGCGCAGTTAGCACTACCGCTTATCTTGTCGTTCACGAACACCAGCGGGCTCGGACTCTGTCCGTAGGACACAGTAGCGCGGTTTCCGGACCTTACACTTGACCATCCAAGCCGCTAGATCTGCCATTAATAACAGTTTTAATTCGAGTTAGCCAAGGGTTAAAGAGATTGGTTGCTGTTTTTGCCTTTCGATAGGCCTGTCTGGGTTGAACGAGGGACGGCTGCTGACAGCTTATTATGACTCGCAAGCGTCTGGGCTAACAACGTAGTGTATGCTAAATAGCACGGTATGATTCATTCGATTAAAATACTAAGTAGACCGTACTAGA"

a_count = 0 
c_count = 0
g_count = 0
t_count = 0


for base in DNA:
    if base == "A":
        a_count += 1
    elif base == "C":
        c_count += 1
    elif base == "G":
        g_count += 1
    else:
        t_count += 1

print(a_count, c_count, g_count, t_count)

x = 3
y = 3 

print(x == y)